### ISSUE TITLE
Route change sets wrong MX record. 

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/cpanel-addon#10]
When using the **"MX Entry**" option in cpanel. Changing the routing from "local" OR  "auto" > "remote" triggers the addon to incorrectly set the MX record on the domain to the server's hostname. 

In this scenario,the correct behavior is to make no change to the MX record - as the user has chosen to use external MX records. If anything, this should remove the domain from the spam experts cluster but not make any changes to the MX.

An example would be that a user might take some time to add each of his new external MX records and save the changes - then set the routing to remote. Nothing changes in the interface initially, so the user is not aware that the MX has changed - but in the background your plugin removes all the MX records and adds one single record pointing to the cpanel server.

### Steps to replicate

From admin console:

1. Install addon
1. Configure the addon
1. Ensure that the "**Add/Remove a domain when the email routing is changed in Cpanel"** is set
1. Ensure that the **"Automatically change the MX records for domains"** is set.
1. Create a New Account 
1. Ensure the account is a resseller and at it own itself 
1. Check that the domain was added to the spam filter interface 
1. Check MX records from `/var/named/example.com.db` (or refresh page) 
1. Notice that the MX records of the spam filter (set in the configuration page) have been set for that domain

From user console:

1. Login with the new account
1. Go to MX Entry
1. Add new MX record that IS NOT one of the ones filled in the configuration page
1. Select "Remote Mail Exchanger" and click "Change"
1. Check MX records from `/var/named/example.com.db` (or refresh page)

### Expected behavior

The MX records of the spam filter should be removed and the one that the user has added manually should be kept. 

Only the SE MX records should be removed and only IF there are NO other MX records left we should add the cpanel server as a record.

### Actual behaviour

All the MX records are removed and replace by the cpanel server.

**Comment by for93t** [comment]
@ashleyse2016 , what's the status of the "Add/Remove a domain when the email routing is changed" option in the add-on configuration?

**Comment by ashleyse2016** [comment]
```
spf_record=""
default_ttl="3600"
language="en"
ssl_enabled="1"
auto_update="1"
auto_add_domain="1"
auto_del_domain="1"
provision_dns="1"
set_contact="1"
handle_extra_domains="1"
add_extra_alias="0"
use_existing_mx="0"
handle_only_localdomains="1"
redirectback="0"
add_domain_loginfail="1"
bulk_force_change="1"
bulk_change_routing="1"
handle_route_switching="1"
disable_reseller_access="0"
use_ip_address_as_destination_routes="0"
add_spf_to_domains="0"
lastupdatecheck="1487462400"
```

**Comment by for93t** [comment]
So that setting is switched on (`handle_route_switching=1`). It means that when the domain MX status was changed to `remote` the add-on attempts to delete the domain from the spamfilter. The deletion procedure includes MX records revert step (`provision_dns=1`). The domain's MX revert step gets the domain's destination routes from the spamfilter API and uses it as the new MX records for the domain. The domain itself gets deleted from the spamfilter.

So current behavior is logical and in line with previous requirements. If you want this changed please explain how exactly it should handle cases like that. Now it does not look like a bug to me.

**Comment by ashleyse2016** [comment]
The problem here i believe is the way its handled. For example, if end users decide to use "Remote Mail Exchanger", they will often first add the records, and only then set it to remote. That last step of setting to remote, will then cause the MX record to be set to the server hostname instead of having it set to their chosen remote records.

**Comment by alexkiro** [comment]
We'll be doing a review of the current behavior. Will add all the necessary details here after.

**Comment by dreasvandonselaar** [comment]
I do believe there is a bug here. The documentation says for "Add/Remove a domain when the email routing is changed in cPanel":
`When the email routing is being changed in the “Edit MX records” setting, you can have the addon automatically remove the domain if it is set to anything but local or add the domain if it is switched to local.`

This does not mention about changing/reverting the MX records when switching from "local" to "remote". If you have "Do not protect remote domains" enabled, and someone switches from "local" to "remote", all we should do is delete the domain from SpamExperts. Reverting the cPanel MX records to point to the cPanel server does not make sense, as cPanel would not accept any email (as it's set remote). Hence the correct behavior would be to delete the domain and ignore the existing MX records in such case. Alternatively we could check if the existing cPanel MX records point to SpamExperts, and if so still do the revert (but not if there are non-SpamExperts records).

**Comment by for93t** [comment]
Current behavior was intentionally introduced in one of the previous bug fixes. See our internal ticket `#28201` for details.

**Comment by alexkiro** [comment]
I've updated the description with the steps to replicate and expected behavior.

**Comment by adaivan** [comment]
Client mentioned this issue is still occurring. Details to follow.
Whmcs 795469

**Comment by alexkiro** [comment]
> Client mentioned this issue is still occurring. Details to follow.
> Whmcs 795469

@adaivan please open a new issue instead of opening this one.
