### ISSUE TITLE
Unable to remove domains from cPanel plugin

### ISSUE THREAD

**Issue by AlexandraSE** [SpamExperts/cpanel-addon#17]
### Version information
Cpanel v11.64.0.24

### Steps to replicate

 1. Try to remove a domain that has not been added to the SpamExperts interface
 2. cPanel error log files contains the following:
16-Jun-2017 14:54:56 UTC] PHP Strict Standards: Redefining already defined constructor for class SpamFilter_Hooks 

### Other notes
Not sure if there are any details that I can add here

**Comment by for93t** [comment]
Fixed in https://github.com/SpamExperts/cpanel-addon/commit/8eeaa2a301fd3c36559aca49fef10ae2532b0fbb

**Comment by Agoodfella** [comment]
Verified.

The initial issue cannot be reproduced on the latest plugin version.
