### ISSUE TITLE
Domains list is not displayed on cPanel interface

### ISSUE THREAD

**Issue by claudiapetre** [SpamExperts/cpanel-addon#18]
### Version information
cPanel version v66.0.6

### Steps to replicate

 1. From the list account list page, go to CP and click on our addon

### Actual result
 2. The loader will remain on the page and the list is not displayed
 3. In console, a javascript error related to jQuery is displayed

### Expected result
 4. The list of domains should be displayed

### Other notes
 5. I check the fix on current, stable and edge.

**Comment by lorentina** [comment]
Fix verified on current, stable and edge. No errors occurred, the list of domains is displayed as expected.

**Comment by ruy-silva** [comment]
Hello, it's working on WHM but not in cPanel:

Please wait....

Loading 
Loading your domainnames
Please contact support if this page doesn't load! 


Support
Information
Controlpanel: Cpanel v11.66.0.8
PHP version: 5.6.30
Addon version: 3.0.96517
