### ISSUE TITLE
Stop using deprecated accesshash authentication method

### ISSUE THREAD

**Issue by SebaDA** [SpamExperts/cpanel-addon#23]
### Version information

Controlpanel: Cpanel v66.0 
PHP version: 5.6.30 
Addon version: 3.0.96529 

cPanel changed the behavior of the "accesshash" auth methods and our Addon doesn't seem to support this, so it fails when accessing the WHM API.

The solution to the problem, as provided by the client:

-     on WHM "Tweak Settings" activate the "Allow deprecated WHM accesshash authentication" option.
-     If needed, under "Remote Access Key" ( now available, after the last step) click "Generate New Key". 

cPanel is deprecating this auth method so the plugin will eventually fail permanently if the new method ( API Tokens) is not configured.

We need to make sure that our Addon is working fine with these changes.

### Acceptance criteria 

 - [ ] We need to modify the installer to generate a token using the new methods 
 - [ ] We need to ensure that people updating to the new version of the addon will still get the token and everything still works
 - [ ] There is no need to support the old accesshash 
 - [ ] If possible the token should be revoked on uninstall
 - [ ] If the token is no longer valid or has been removed an error should be shown 

### Other notes 

CR: 8

**Comment by ashleyse2016** [comment]
their (cPanel) plan seems to indicate they remove this method in .68 . So this should be a higher priority. 
https://documentation.cpanel.net/display/CKB/cPanel+Deprecation+Plan

**Comment by alexkiro** [comment]
FWIW, cPanel support indicated that we can still create token cmdline in our installer using something like this:

```
whmapi1 api_token_create token_name=prospamfilter acl-1=kill-acct acl-2=list-acct
```

So we will need to (a) modify installer to use this method to generate a token for the addon and (b) change the code to use the new authentication method instead of access hash.

**Comment by alexkiro** [comment]
FWIW, this was pushed in the September because the current system might be removed completely in October.

**Comment by catalinDonici** [comment]
Sorry for the late reply. 

Using the new installer from scratch works fine, however I thing there are some issues when existing customers will try and update to the new addon version. 

My test case is:
* install the stable version of the addon. 
```
wget -N https://download.seinternal.com/integration/installers/cpanel/installer.sh && bash installer.sh
```
* access the addon using the interface and update to testing using `Force a reinstall even if the system is up to date.` _(There doesn't seem to be a new version in testing)_

Issue: a new `.accesstoken` is not created, therefore I suspect the new installer is not used.

**Comment by catalinDonici** [comment]
@claudiapetre, when does the installer gets updated?

**Comment by claudiapetre** [comment]
When update is initialized, new build will be downloaded from our server, files will be replaced and the install will start (in the background). This is the reason why we have the message to wait for at least 30 seconds, to give time to the addon to be re-installed using new files.

**Comment by catalinDonici** [comment]
A few more questions:

* IIUC, customers that will install the addon (using `bin/installer/installer.sh`) will start using the `.accesstoken`, but what happens to the customers that will try to update to the latest version? How would they get the new changes? 
* Does the script need to be manually updated by the sysadmin on the download server?

**Comment by catalinDonici** [comment]
On `edge.cpanel` a fresh install of the addon failed 

```root@edge [~]# bash installer.sh
Installing ProSpamFilter for cPanel..
Generating access token for the WHM API..Unable to create token.   reason: "The system failed to create the API token: Invalid or unauthorized ACL specified: list-acct"```

**Comment by catalinDonici** [comment]
On `current.cpanel` failed with:

```
+ echo 'Unable to create token.   reason: "The system failed to create the API token: An API token with the name “prospamfilter” already exists."'
Unable to create token.   reason: "The system failed to create the API token: An API token with the name “prospamfilter” already exists."
+ exit 1
```

There is no .accesstoken 

```
root@current [~]# ls -la | grep .access
-rw-rw----  1 root root    990 Oct  1 08:02 .accesshash
-rw-------  1 root root    990 Oct  1 07:58 .accesshash_bk
root@current [~]#
```

**Comment by catalinDonici** [comment]
Verified.
