### ISSUE TITLE
Ajax requests are broken

### ISSUE THREAD

**Issue by SebaDA** [SpamExperts/cpanel-addon#24]
### Version information

Controlpanel: Cpanel v11.66.0.15
PHP version: 5.6.30
Addon version: 3.0.96529

### Steps to replicate

1. Domain List 
2. Toggle Protection

### Actual result 

> {"message":"The protection status of domain.tld has been changed to protected<\/strong>","status":"success"}

> {"message":"The protection status of domain.tld has been changed to unprotected<\/strong>","status":"success"}

### Expected result

Clean text

**Comment by lorentina** [comment]
Fix verified on current, stable and edge.
