### ISSUE TITLE
API password incorrectly encoded

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/cpanel-addon#25]
A user is getting this error in cpanel when trying to use the Migrate option: `The API credentials provided are incorrect, please specify a valid API username and password` he sais the password is correct. But the url encodes the @ in his password to `2%` 

### Version information
Controlpanel: Cpanel v11.66.0.15
PHP version: 5.6.30
Addon version: 3.0.96529
Diagnostics

### Steps to replicate

 1. Create an admin account with the special character @ in it's password.
 2.  Try to migrate account from the Cpanel migrate option

### Actual result
`The API credentials provided are incorrect, please specify a valid API username and password
`
The url encodes the @ in his password to `2%`
### Expected result

the used password should be the correct one

### Other notes
[WHMCS](https://my.spamexperts.com/admin/supporttickets.php?action=view&id=179716)

**Comment by alexkiro** [comment]
FWIW the password IS correctly encoded, so there must be another problem here.

**Comment by for93t** [comment]
I'm unable to reproduce the issue on our dev/testing environment.
