### ISSUE TITLE
JSON response when protecting a domain

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/cpanel-addon#26]
### Version information

```
Controlpanel: Cpanel v11.64.0.38
PHP version: 5.6.30
Addon version: 3.0.96529
```
### Steps to replicate

1: Update to latest version
2: Click Domain list
3: Click "Toggle Protection"

### Actual result

White screen with JSON response in interface 
```{"message":"The protection status of cpanel.example.com has been changed to unprotected<\/strong>","status":"success"}```

### Expected result
To stay on the domain list screen and show a response in HTML not JSON.

**Comment by for93t** [comment]
Fixed in #24.
