### ISSUE TITLE
JSON parse failed when changing MX routing 

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/cpanel-addon#29]
### Version information
```
Controlpanel: Cpanel v11.56.0.52
PHP version: 5.4.31
Addon version: 3.0.96531
```

### Steps to replicate

 1. Install version of cPanel 11.56.0.52
 2. Install addon
 3. Add /protect a domain
 4. Navigate to MX routing on domain in cPanel
 5. Change routing

### Actual result

`JSON parse failed`

### Expected result
Correct set. 

### Other notes

I have not been able to replicate this as my testing version is higher than `11.56.0.52` so cannot confirm fully if this is an addon issue or something else. 

Partial logs from 3rd party that indicated the issue:
```
[2017-09-20 10:59:35 +0100] info [cpanel] STDERR output from hook: /usr/local/prospamfilter/bin/hook.php
[2017-09-20 10:59:35 +0100] info [cpanel] Cannot get grandparent of grandparent process name.
Cannot get grandparent of grandparent process name.
Cannot get grandparent of grandparent process name.
Cannot get grandparent of grandparent process name.
Cannot get grandparent of grandparent process name.
Cannot get grandparent of grandparent process name.
Cannot get grandparent of grandparent process name.
Cannot get grandparent of grandparent process name.
Cannot get grandparent of grandparent process name.
[2017-09-20 10:59:35 +0100] info [cpanel] End STDERR from hook 
```

Please verify if this is indeed caused by the addon and what needs resolving.

**Comment by alexkiro** [comment]
Unfortunately we can only [support](https://kb.spamexperts.com/29941-integration/227827-cpanel-addon#system-requirements) stable/release/current versions of cPanel at this time. 

I would suggest updating to the cPanel version.
