### ISSUE TITLE
Incompatibility with WHM 56.0

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/cpanel-addon#32]
### Version information

WHM 56.0

### Steps to replicate

 1. Install addon
 2. View list domains

### Actual result

```
Warning: Invalid argument supplied for foreach() in /usr/local/prospamfilter/library/SpamFilter/PanelSupport/Cpanel.php on line 1677 
```

### Expected result

Functionality  on domain lists on version 56.0 WHM

### Other notes

Untested no access to 56.0 testing server

**Comment by alexkiro** [comment]
Unfortunately we can only [support](https://kb.spamexperts.com/29941-integration/227827-cpanel-addon#system-requirements) stable/release/current versions of cPanel at this time. 

I would suggest updating to a newer cPanel version.
