### ISSUE TITLE
Cpanel not displaying reseller domains

### ISSUE THREAD

**Issue by AndreiCristianIT** [SpamExperts/cpanel-addon#35]
### Version information
Cpanel v11.68.0.9
PHP version: 5.6.30
Addon version: 3.0.96549
### Steps to replicate

 1.login to WHM > Profesional Spam Filter > List Domains

### Actual result
That page will only list domain which are owned by root. domains owned by reseller did not appear on SpamExperts List Domains.

### Expected result
List all domains, including re-seller.

**Comment by for93t** [comment]
I've made a request to the cPanel support - the ticket id is 9015691. Now waiting for their response.

**Comment by for93t** [comment]
In order to permit access to all domains on the server the API access token must have `all` permissions granted. Current access level (` acl-1=list-accts acl-2=basic-system-info`) is not enough.

**Comment by Agoodfella** [comment]
After the changes made in this ticket the issue is no longer reproducible.

Fix verified on cpanel v68.
