### ISSUE TITLE
Addon does not display domain list/ gives errors when running update

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/cpanel-addon#36]
### Version information

Controlpanel: Cpanel v56.0
PHP version: 5.4.31
Addon version: 3.0.96549

### Steps to replicate

 1.Client is trying to access the domains list,however this does not load

### Actual result
The domain list does not load

### Expected result
The page  should correctly display the domains.

### Other notes

The client also tried to run the update the addon and had some errors:

[install_logs.txt](https://github.com/SpamExperts/cpanel-addon/files/1442228/install_logs.txt)

WHMCS: 479373

**Comment by alexkiro** [comment]
We only support stable/release/current for our addon. LTS is not supported, furthermore this specific version has reached EOL last month. 

Please see KB [article](https://kb.spamexperts.com/29941-integration/227827-cpanel-addon#downgrade-instructions) for downgrade instructions.
