### ISSUE TITLE
Test add-on compatibility with cPanel & WHM v.70

### ISSUE THREAD

**Issue by for93t** [SpamExperts/cpanel-addon#42]
In the Q1 2018 cPanel & WHM 70 is anticipated to reach all release stages (current, release and stable) so it would be good to make sure that our add-on is fully compatible with it. 

According to the [Release notes](https://documentation.cpanel.net/display/70Docs/70+Release+Notes) there are no breaking changes so this task does not require any development work, just testing.

**Comment by lorentina** [comment]
Verified add-on compatibility with the new version (v.70) on current, release and stable.
No issues occurred during testing.
