### ISSUE TITLE
Cpanel Addon only displays main domain instead of the full domain list 

### ISSUE THREAD

**Issue by narciswork** [SpamExperts/cpanel-addon#43]
### Version information
Controlpanel: Cpanel v11.68.0.29
PHP version: 5.6.30
Addon version: 3.0.96563

### Steps to replicate

 1. Client is trying to access the domains list,however this will only list his main domain and not others added.

### Actual result
The list does not fully display

### Expected result

The client to see the full domain list

[debug.log.txt](https://github.com/SpamExperts/cpanel-addon/files/1724459/debug.log.txt)

[Cpanel issue Diagnostics page.txt](https://github.com/SpamExperts/cpanel-addon/files/1724461/Cpanel.issue.Diagnostics.page.txt)
### Other notes

https://my.spamexperts.com/admin/supporttickets.php?action=view&id=196621

**Comment by claudiapetre** [comment]
"Process addon-, parked and subdomains" option was not enabled in addon configuration. This issue is invalid.
