### ISSUE TITLE
PHP Fatal error/ 500 Internal Server Error 

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/cpanel-addon#45]
### Version information
Controlpanel: Cpanel v60.0
PHP version: 5.6.20
Addon version: 3.0.96563

### Steps to replicate

 1. Client receives the following error when he's logging in from the addon to the Spam Experts dashboard.

### Actual result
PHP Fatal error: Call to a member function whm_api() on null in /usr/local/prospamfilter/library/SpamFilter/PanelSupport/Cpanel.php on line 1645 

### Other notes
WHMCS: https://my.spamexperts.com/admin/supporttickets.php?action=view&id=198477

**Comment by claudiapetre** [comment]
Please, advise the client to upgrade his WHM or to downgrade the addon (https://kb.spamexperts.com/29941-integration/227827-cpanel-addon#downgrade-instructions) because his WHM version doesn't support authentication using tokens.
