### ISSUE TITLE
Error The security token is missing from your request

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/cpanel-addon#46]
### Version information
Cpanel version: 11.68.029
PHP version: 5.6.30
Addon version: 3.0.96563

### Steps to replicate

 1.  Client goes to domain list via addon and tries to login to the SE interface

### Actual result
Error: The security token is missing from your request

### Expected result
The client should be able to login without any issues

### Other notes
Access details on WHMCS #826721

**Comment by claudiapetre** [comment]
AntiSpam API URL was not set and did not exist at all in addon settings. We have a client-side validation for this field, so this was done in a different way, but we couldn't replicate it on our testing server. After value for AntiSpam API URL was set up, the issue was fixed.
