### ISSUE TITLE
Error: There are no domains on this server

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/cpanel-addon#48]
### Version information

cPanel version

### Steps to replicate

 1. Client set up the Cpanel addon
2.  When they try to access the Control Panel  from Cpanel, they get the mentioned error.

### Actual result
Error: There are no domains on this server

### Other notes

PHP version:
OK!
PHP extensions:
OK!
Configuration binary:
OK!
Configuration permissions:
OK!
Panel version:
OK!
Addon version:
OK!
Hashes:
OK!
Hooks:
OK!
Symlinks:
OK!
Controlpanel API:
Unable to communicate with the controlpanel API
CRITICAL
Spamfilter API:
OK!

Will add details in slack
WHMCS: https://my.spamexperts.com/admin/supporttickets.php?action=view&id=207021

**Comment by for93t** [comment]
@adaivan, a debug log is required to investigate the issue. In the WHMCS ticket the client tries to check `/etc/prospamfilter/debug` for log entries but that file is just a flag indicating that the add-on should write verbose logs into the syslog. So the log entries can be seen in `/var/log/debug` (if that file path is not overridden in their syslog config).

NB: At this point, there is no evidence that the "Warning: Unknown: Failed to write session data" warning is related to the control panel API connection problem.
