### ISSUE TITLE
SpamExpert SPF records is not added while creating new cPanel account/domain protection

### ISSUE THREAD

**Issue by narciswork** [SpamExperts/cpanel-addon#49]
### Version information
cpanel V72, V74

### Steps to replicate

Client is unable to add SpamExpert spf record while adding new cPanel account or creating new addon domain under cPanel user account. 

The indication is that the version might be the cause, as these were not tested.
Client runs most of our servers are on cPanel 72 and  they have 3 servers on cPanel 74.

### Expected result
SPF to be added with domain entry 'Set SPF records for domains'

**Comment by SebaDA** [comment]
This is not a bug. The client was adding the domains to the cPanel server, not to filtering. So the addon was not being used here. The addon will only update the settings in case the domain is protected. When you add a domain to the cPanel server itself, this will take the settings that you have on the cpanel server.
