### ISSUE TITLE
Update cPanel addon to work with PHP 7.2

### ISSUE THREAD

**Issue by SebaDA** [SpamExperts/cpanel-addon#51]
### Version information

Controlpanel: Cpanel v11.76.0.12
PHP version: 7.2.7
Addon version: 3.0.96563

### Steps to replicate

 1. Install the cPanel addon on a cpanel server v11.76.0.12 with PHP version 7.2.7
2. Run Eg: diagnostics. 

Alternative steps: log into WHM and clicking Spam Experts plugin as root.

### Actual result
`PHP version:
OK!
PHP extensions:
OK!
Configuration binary:
OK!
Configuration permissions:
OK!
Panel version:
OK!
Addon version:
OK!
Hashes:
OK!
Hooks:
OK!
Symlinks:
OK!
Controlpanel API:
OK!
Spamfilter API:
OK!
Warning: count(): Parameter must be an array or an object that implements Countable in /usr/local/prospamfilter/library/Cpanel/PublicAPI.php on line 347 `

### Expected result
No error to be returned

### Other notes
Client mentioned that there are other similar servers using the addon and not having this problem.

**Comment by SebaDA** [comment]
these issues seem to be intermittent.

**Comment by tiagomreis** [comment]
**Version information**
Controlpanel: Cpanel v11.78.0.15
PHP version: 7.2.7
Addon version: 3.0.96563

Same issue when we access to SpamFilter on WHM.

Warning: count(): Parameter must be an array or an object that implements Countable in /usr/local/prospamfilter/library/Cpanel/PublicAPI.php on line 347

**Comment by LaurentiuTeodorescu** [comment]
```
Controlpanel: Cpanel v11.98.0.4
PHP version: 7.3.28
Addon version: 3.0.96604
```
