### ISSUE TITLE
Access hash usage leads to domains not showing in the domain list

### ISSUE THREAD

**Issue by SebaDA** [SpamExperts/cpanel-addon#95]
### Version information

cPanel: V 80.0.20

### Steps to replicate

 1. Install the cPanel addon on the cPanel server
2. set up the addon
3. try to see the domain list

### Actual result

Domain list not showing up

### Expected result

The domains should populate the domain list.

### Other notes

Logs show:

```
sed -n '1,15p' /usr/local/prospamfilter/bin/cpanel/createacct.php
<?php
die;
require_once realpath(dirname(FILE ) . '/../../') . '/application/bootstrap.php';
$apiAccessHash = file_get_contents('/root/.accesshash');
$api = Cpanel_PublicAPI::getInstance(array(
'service' => array(
'whm' => array(
'config' => array(
'user' => 'root',
'hash' => $apiAccessHash,
),
```

The /root/accessHash was deprecated, so we should deprecate this as well. 

461793
333156

**Comment by dbistriceanu** [comment]
Access hashes have not been used since (#23). And the addon does not support cPanel v80 at the moment (#51).
